### ISSUE TITLE
Scribing ToDo

### ISSUE THREAD

**Issue by eigenscribe** [Eigenscribe-Archive/projLevitate#11]
- [x] [Markov Chains Clearly Explained! Part - 1](https://www.youtube.com/watch?v=i3AkTO9HLXo&list=TLPQMTgwMTIwMjMWNHnxbFgtrA&index=2) 📺
- [ ] [Information entropy | Journey into information theory | Computer Science | Khan Academy](https://www.youtube.com/watch?v=2s3aJfRr9gE&list=TLPQMDEwNTIwMjOUaP2TjkuH8A&index=2) 📺
- [ ] [Probability Models](https://www.math.wustl.edu/~feres/Math450Lect01.pdf) 📄
- [ ] Steve Brunton Complex Analysis Playlist
